### ISSUE TITLE
Testing linear strategy

### ISSUE THREAD

**Issue by pgrandjean** [sweet-delights/hybrid-platforms-conductor#118]
For some reason, the following is failing:
```
[2022-01-28 14:46:23 (PID 57294 / TID 77900)] ERROR - [ LinearStrategy ] - [ #< Test linear_strategy - Platform ansible-dsc > ] - Uncaught exception during test: string length (16691) exceeds the limit 128
/usr/local/lib/ruby/2.7.0/time.rb:372:in `_parse'
/usr/local/lib/ruby/2.7.0/time.rb:372:in `parse'
/home/jenkins/workspace/ATI_dsc-platforms-repos_master/vendor/bundle/ruby/2.7.0/gems/hybrid_platforms_conductor-33.9.2/lib/hybrid_platforms_conductor/hpc_plugins/test/linear_strategy.rb:37:in `block in test_on_platform'
/home/jenkins/workspace/ATI_dsc-platforms-repos_master/vendor/bundle/ruby/2.7.0/gems/hybrid_platforms_conductor-33.9.2/lib/hybrid_platforms_conductor/hpc_plugins/test/linear_strategy.rb:19:in `each'
/home/jenkins/workspace/ATI_dsc-platforms-repos_master/vendor/bundle/ruby/2.7.0/gems/hybrid_platforms_conductor-33.9.2/lib/hybrid_platforms_conductor/hpc_plugins/test/linear_strategy.rb:19:in `test_on_platform'
/home/jenkins/workspace/ATI_dsc-platforms-repos_master/vendor/bundle/ruby/2.7.0/gems/hybrid_platforms_conductor-33.9.2/lib/hybrid_platforms_conductor/tests_runner.rb:328:in `block in run_tests_on_subjects'
/home/jenkins/workspace/ATI_dsc-platforms-repos_master/vendor/bundle/ruby/2.7.0/gems/hybrid_platforms_conductor-33.9.2/lib/hybrid_platforms_conductor/tests_runner.rb:363:in `block (2 levels) in run_tests_on_subjects'
/home/jenkins/workspace/ATI_dsc-platforms-repos_master/vendor/bundle/ruby/2.7.0/gems/hybrid_platforms_conductor-33.9.2/lib/hybrid_platforms_conductor/parallel_threads.rb:49:in `block (3 levels) in for_each_element_in'
/home/jenkins/workspace/ATI_dsc-platforms-repos_master/vendor/bundle/ruby/2.7.0/gems/hybrid_platforms_conductor-33.9.2/lib/hybrid_platforms_conductor/parallel_threads.rb:39:in `loop'
/home/jenkins/workspace/ATI_dsc-platforms-repos_master/vendor/bundle/ruby/2.7.0/gems/hybrid_platforms_conductor-33.9.2/lib/hybrid_platforms_conductor/parallel_threads.rb:39:in `block (2 levels) in for_each_element_in'
```

**Comment by Muriel-Salvan** [comment]
I managed to reproduce it. I will work on a fix.
